create database customer_behaviour;
use customer_behaviour;
select * from customer;

# Q1. What is the total revenue generated by male vs. female customers?
select Gender, SUM(`Purchase_Amount_(USD)`) as Revenue 
from customer 
group by gender;

# Q2. Which customers used a discount but still spent more than the average purchase amount? 
select c_id, Purchase_Amount_USD 
from customer 
where Discount_Applied = 'Yes' and Purchase_Amount_USD >= (select avg(Purchase_Amount_USD) from customer);

# Q3. Which are the top 5 products with the highest average review rating?
SELECT Item_Purchased,AVG (Review_Rating) AS Avg_Rating
FROM customer
GROUP BY Item_Purchased
ORDER BY Avg_Rating DESC
LIMIT 5;

# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select Shipping_Type, round(avg(Purchase_Amount_USD),2) 
from customer 
where Shipping_Type in ('Standard', 'Express') 
group by Shipping_Type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select Subscription_Status, 
count(c_id) as total_customers,
avg(Purchase_Amount_USD) as avg_spend, 
sum(Purchase_Amount_USD) as total_revenue
from customer
group by Subscription_Status;         

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?     
SELECT Item_Purchased,ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS Discount_Percentage
FROM customer
GROUP BY Item_Purchased
ORDER BY Discount_Percentage DESC
LIMIT 5;                                                                                                 

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select c_id, Previous_Purchases,
CASE
when Previous_Purchases = 1 then 'New'
when Previous_Purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer)
select customer_segment, count(*) As 'Number of customers'
from customer_type
group by customer_segment;

# Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(c_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(c_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

# Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(c_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT 
    age,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM customer
GROUP BY age
ORDER BY total_revenue desc;






